#!/bin/env bash

# Author: Sam Whang
# File  : salary.sh
# Usage : ./salary
# Info  : calculating costs of living for current salary

# Print formatting options
bold="\e[1m"
end="\e[0m"

# string outputs
header="+===========+===========+===========+===========+===========+
| Total In  | Total Out | Total Bi  | Take Home | Remaining |"
divide="+-----------+-----------+-----------+-----------+-----------+"
format="| %9s | %9s | %9s | %9s | %9s |\n" 

echo "Average Monthly Expense: ~1,600"
echo "+=====+======+=====+======+======+======+=====+=====+=======+"
echo "| MON | RENT | CAR | LOAN | WIFI | FOOD | GYM | GAS | TOTAL |"
echo "+=====+======+=====+======+======+======+=====+=====+=======+"
echo "| FEB | 500  | 250 | ~250 | ~80  | ~200 | ~40 | ~25 | ~1400 |"
echo "+-----+------+-----+------+------+------+-----+-----+-------+"
echo
echo "+========+=========+========+===========+========+"
echo "| Tot In | Tot Mon | Tot Bi | Take Home | Remain |"
echo "|========+=========+========+===========+========+"
echo "| 30,000 | 2,500   | 1,250  | ~1,000    | ~500   |"
echo "+--------+---------+--------+-----------+--------+"
echo "| 35,000 | ~2,917  | ~1,458 | ~1,200    | ~800   |"
echo "+--------+---------+--------+-----------+--------+"
echo "| 40,000 | ~3,333  | ~1,667 | ~1,400    | ~1,200 |"
echo "+--------+---------+--------+-----------+--------+"
echo "| 45,000 | 3,750   | 1,875  | ~1,600    | ~1,600 |"
echo "+--------+---------+--------+-----------+--------+"

echo "Date   | Total   | Takehome| Taxes  | Retire| Other|Bnfts"
echo "---------------------------------------------------------"
echo "OCT 13 | 1754.11 | 1403.65 | 289.94 | 52.50 | 4.11 | 3.91"

# write lines for each iteration and caluclate using bc
printf "$bold%s$end\n%s\n" "$header" "$divide"
for total in `seq 30000 5000 100000`; do
  monthly=$(($total/12))
  bimonth=$(($monthly/2))
  # if bc doesn't work use awk
  # takehome=$(echo "$bimonth*0.8125" | bc)
  # remaining=$(echo "$takehome*2-1400" | bc)
  takehome=$(awk "BEGIN {print \"$bimonth\"*0.8125}")
  remaining=$(awk "BEGIN {print \"$takehome\"*2-1400}")
  printf "$format" "$total" "$monthly" "$bimonth" "$takehome" "$remaining"
  echo "$divide"
done

