#!/usr/bin/env bash


__getVC() {
  echo " --- Valley City Listings --- "
  curl --silent http://bison6cinema.com/valley-city/ |\
    grep -o '<h4 class=\"heading14\">.*</h4>' |\
    sed 's/\(<[^\>]*>\|<\/[^\>]*>\)//g'
}

__getJT() {
  jt=$(curl --silent http://bison6cinema.com)
  echo " ---  Jamestown Listings  --- "
  grep -o '18\">.*</' <<< "$jt" | sed 's/\<[^\>]*>\|<\///g'
}

__getUP() {
  if [ ! -z ${jt+x} ]; then
    jt=$(curl --silent http://bison6cinema.com)
  fi
  echo " ---    Upcoming Movie    --- "
  grep -o '<span>.*</span>' <<< "$jt" | sed 's/\(<[^\>]*>\|<br.*>\)//g'  
}

movies() {
  # ---                                                   --- #
  # TODO: want to parse movies by name and get rt scores      #
  # ---                                                   --- #
  local jt=''
  if [[ "$#" == "0" ]]; then
    __getVC &
    __getJT &
    wait
    __getUP
  fi
  
  if [[ "$#" == "1" ]]; then
    case $1 in
      -vc|--valley-city)
        __getVC
        shift
        ;;
      -jt|--jamestown)
        __getJT
        shift
        ;;
      -u|--upcoming)
        __getUP
        shift
        ;;
      *)
        echo "usage: movies [-vc|--valley-city] 
              [-jt|--jamestown]
              [-u|--upcoming]"
        shift
        ;;
    esac
  fi
}
